const motivationalQuotes = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The harder the conflict, the greater the triumph. – George Washington",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "Act as if what you do makes a difference. It does. – William James",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "With the new day comes new strength and new thoughts. – Eleanor Roosevelt",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "You just can’t beat the person who never gives up. – Babe Ruth",
    "Believe you can and you’re halfway there. – Theodore Roosevelt",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "The secret of getting ahead is getting started. – Mark Twain",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "We may encounter many defeats but we must not be defeated. – Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. – Johann Wolfgang Von Goethe",
    "Quality is not an act, it is a habit. – Aristotle",
    "You are what you do, not what you say you’ll do. – Carl Jung",
    "The best way to predict the future is to invent it. – Alan Kay",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only difference between ordinary and extraordinary is that little extra.",
    "It’s not whether you get knocked down. It’s whether you get up. – Vince Lombardi",
    "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
    "We generate fears while we sit. We overcome them by action. – Dr. Henry Link",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller"
];
